[improve][ci] check python doc syntax (#38)
* tidy repo settings

Signed-off-by: tison <wander4096@gmail.com>

* cancelled should not pass the require check

Signed-off-by: tison <wander4096@gmail.com>

* add check-and-lint job

Signed-off-by: tison <wander4096@gmail.com>

* F yaml

Signed-off-by: tison <wander4096@gmail.com>

Signed-off-by: tison <wander4096@gmail.com>

diff --git a/.github/workflows/ci-pr-validation.yaml b/.github/workflows/ci-pr-validation.yaml
--- a/.github/workflows/ci-pr-validation.yaml
+++ b/.github/workflows/ci-pr-validation.yaml
@@ -27,6 +27,24 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  check-and-lint:
+    name: Lint and check code
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v4
+        with:
+          python-version: 3.x
+      - name: Install deps
+        run: pip install -U pydoctor
+      - name: Check docs syntax
+        run: |
+          pydoctor --make-html \
+            --html-viewsource-base=https://github.com/apache/pulsar-client-python/tree/main \
+            --docformat=numpy --theme=readthedocs \
+            --intersphinx=https://docs.python.org/3/objects.inv \
+            --html-output=apidocs \
+            pulsar
 
   unit-tests:
     name: Run unit tests
@@ -237,12 +255,26 @@ jobs:
           ls -l *.dll
           python -c 'import pulsar; c = pulsar.Client("pulsar://localhost:6650"); c.close()'
 
-
-  # Job that will be required to complete and depends on all the other jobs
   check-completion:
     name: Check Completion
     runs-on: ubuntu-latest
-    needs: [unit-tests, linux-wheel, mac-wheels, windows-wheels]
-
+    if: ${{ always() }}
+    needs: [
+      check-and-lint,
+      unit-tests,
+      linux-wheel,
+      mac-wheels,
+      windows-wheels
+    ]
     steps:
-      - run: true
+      - run: |
+          if [[ ! ( \
+                    "${{ needs.check-and-lint.result }}" == "success" \
+                  && "${{ needs.unit-tests.result }}" == "success" \
+                  && "${{ needs.linux-wheel.result }}" == "success" \
+                  && "${{ needs.mac-wheels.result }}" == "success" \
+                  && "${{ needs.windows-wheels.result }}" == "success" \
+                ) ]]; then
+              echo "Required jobs haven't been completed successfully."
+              exit 1
+            fi
